#!/usr/bin/python

# CLI interface to tradking account and stock quotes.
# Author: Vinay Sanjekar

import sys
import os, argparse
from pprint import pprint

import tradeking.tradeking

argparser = argparse.ArgumentParser(description='aitrader')
subparsers = argparser.add_subparsers(dest="mode") 
parser_tk = subparsers.add_parser('tk')
parser_tk.add_argument('-a','--all', help='All information', action="store_true", default=False)
parser_tk.add_argument('-b','--brief', help='Brief information', action="store_true", default=True)
parser_tk.add_argument('-l','--log', help='Account log', action="store_true", default=False)
parser_tk.add_argument('-o','--orders', help='Account log', action="store_true", default=False)
parser_tk.add_argument('-p','--portfolio', help='Portfolio information', action="store_true", default=False)
parser_tk.add_argument('-s','--symbol', help='Ticker symbol')
parser_tk.add_argument('-u','--user', help='User file')
parser_tk.add_argument('-w','--watchlist', help='Wishlists', action="store_true", default=False)
options = vars(argparser.parse_args())

print options

# TradeKing commands
if options['mode'] == 'tk':
  if options['user']:
    tk = tradeking.tradeking.TradeKing(options['user'])
  else:
    tk = tradeking.tradeking.TradeKing('user.json')
  # "./aitrader.py tk -p"
  if options['portfolio']:
    # tk.get_acc_info()
    tk.get_acc_cash_basis()
    tk.get_acc_balance()
    tk.get_acc_holdings()
  # "./aitrader.py tk -w"
  elif options['watchlist']:
    tk.get_acc_watchlist()
  # "./aitrader.py tk -l"
  elif options['log']:
    tk.get_acc_history()
  # "./aitrader.py tk -o"
  elif options['orders']:
    tk.get_acc_orders()
  elif options['symbol'] is not None:
    # "./aitrader.py tk -s TRLA -a"
    if options['all']:
      tk.get_ticker_quote(options['symbol'])
    # "./aitrader.py tk -s TRLA -b"
    elif options['brief']:
      tk.get_ticker_brief(options['symbol'])
